title = "B153.co"
baseURL = "https://b153.co/"
languageCode = "en-us"
theme = "airspace-hugo"
publishDir = "../"

[menu]

  [[menu.header]]
    weight = 2
    name = "Work"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "Blog"
    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Service"
    url = "/service"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"


  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "contact"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "/blog"


# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "A basement data science club &amp; blog"
    subtitle = "We love data and the work we do."

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "At b153 we believe that all organizations have the capacity to leverage data to drive decision making. Organizations often have large amounts of data but lack the knowledge, skills, and expertise to ensure its appropriate use. Building a data analytics program allows organizations to capitalize on this asset and operate with increased efficiency, transparency, and insight."
    paragraph = ""

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Bloggity Blog Blog"

  [params.feature]
    enable = false
    title = "We believe data is invaluable"
    content = "Take your business to the next level."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "Calgary, Alberta"
      email = "Email: admin@b153.ca"
      phone = "Phone: +1.587.228.6320"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
